import apiUser from "./apiUser.js";
import apiPetType from "./apiPetType.js";
import apiCategory from "./apiCategory.js";
import apiPost from "./apiPost.js";
import apiServive from "./apiService.js";
import apiPet from "./apiPet.js";
import apiProduct from "./apiProduct.js";
import apiOrder from "./apiOrder.js";
import apiUserPet from "./apiUserPet.js";
import apiPetScores from "./apiPetScores.js";
import apiAppointment from "./apiAppointment.js";
import apiOrderItem from "./apiOrderItem.js";
import apiProductReview from "./apiProductReview.js";
import apiPetReview from "./apiPetReview.js";
import apiServiceReview from "./apiServiceReview.js";
import apiCart from "./apiCart.js";
import apiCartItem from "./apiCartItem.js";
import apiPaginate from "./apiPaginate.js";
import apiVnPay from "./apiVnPay.js";
import apiSendEmail from "./apiSendEmail.js";
import apiContact from "./apiContact.js";
import apiNotification from "./apiNotification.js";
import apiPayments from "./apiPayments.js";
import apiVoucher from "./apiVoucher.js";

const apiInitWebRouter = (app) => {
  app.use("/v1/api/user", apiUser);
  app.use("/v1/api/pet-type", apiPetType);
  app.use("/v1/api/category", apiCategory);
  app.use("/v1/api/post", apiPost);
  app.use("/v1/api/service", apiServive);
  app.use("/v1/api/pet", apiPet);
  app.use("/v1/api/product", apiProduct);
  app.use("/v1/api/order", apiOrder);
  app.use("/v1/api/user-pet", apiUserPet);
  app.use("/v1/api/pet-scores", apiPetScores);
  app.use("/v1/api/appointment", apiAppointment);
  app.use("/v1/api/order-item", apiOrderItem);
  app.use("/v1/api/product-review", apiProductReview);
  app.use("/v1/api/pet-review", apiPetReview);
  app.use("/v1/api/service-review", apiServiceReview);
  app.use("/v1/api/cart", apiCart);
  app.use("/v1/api/cart-item", apiCartItem);
  app.use("/v1/api/paginate", apiPaginate);
  app.use("/v1/api/vnPay", apiVnPay);
  app.use("/v1/api/contact", apiContact);
  app.use("/v1/api/notification", apiNotification);
  app.use("/v1/api/email", apiSendEmail);
  app.use("/v1/api/payment", apiPayments);
  app.use("/v1/api/voucher", apiVoucher);
};

export default apiInitWebRouter;
